Ep. 5 - Marketing Mix Modeling: How to create a Marketing Forecaster with EXCEL


https://www.youtube.com/watch?v=7HuMsxJU2u4


https://docs.google.com/spreadsheets/d/1FjXCiEI1yXUA825rkt-Hg_9Ry_dcI1YrkmxLYSJBhT0/edit?pli=1&gid=518075327#gid=518075327

# Criando um simulador

In [87]:
import pandas as pd
# Ler a primeira aba (índice 0)
df = pd.read_excel('../MARKETING MIX MODELING YT.xlsx', sheet_name=0)

df

       Time  sales     FB    TV  Radio       Date
0    Week 1   22.1  230.1  37.8   69.2 2020-01-01
1    Week 2   10.4   44.5  39.3   45.1 2020-01-02
2    Week 3    9.3   17.2  45.9   69.3 2020-01-03
3    Week 4   18.5  151.5  41.3   58.5 2020-01-04
4    Week 5   12.9  180.8  10.8   58.4 2020-01-05
5    Week 6    7.2    8.7  48.9   75.0 2020-01-06
6    Week 7   11.8   57.5  32.8   23.5 2020-01-07
7    Week 8   13.2  120.2  19.6   11.6 2020-01-08
8    Week 9    4.8    8.6   2.1    1.0 2020-01-09
9   Week 10   10.6  199.8   2.6   21.2 2020-01-10
10  Week 11    8.6   66.1   5.8   24.2 2020-01-11
11  Week 12   17.4  214.7  24.0    4.0 2020-01-12
12  Week 13    9.2   23.8  35.1   65.9 2020-01-13
13  Week 14    9.7   97.5   7.6    7.2 2020-01-14
14  Week 15   19.0  204.1  32.9   46.0 2020-01-15
15  Week 16   22.4  195.4  47.7   52.9 2020-01-16
16  Week 17   12.5   67.8  36.6  114.0 2020-01-17
17  Week 18   24.4  281.4  39.6   55.8 2020-01-18
18  Week 19   11.3   69.2  20.5   18.3 2020-01-19
19  Week 20   14.6  147.3  23.9   19.1 2020-01-20
20  Week 21   18.0  218.4  27.7   53.4 2020-01-21
21  Week 22   12.5  237.4   5.1   23.5 2020-01-22
22  Week 23    5.6   13.2  15.9   49.6 2020-01-23
23  Week 24   15.5  228.3  16.9   26.2 2020-01-24
24  Week 25    9.7   62.3  12.6   18.3 2020-01-25
25  Week 26   12.0  262.9   3.5   19.5 2020-01-26
26  Week 27   15.0  142.9  29.3   12.6 2020-01-27
27  Week 28   15.9  240.1  16.7   22.9 2020-01-28
28  Week 29   18.9  248.8  27.1   22.9 2020-01-29
29  Week 30   10.5   70.6  16.0   40.8 2020-01-30

# Adstock(t)= Adstock (t-1)*beta+ Spent(t)

# Dim Ret = Adstock(t) ^Alpha

# Transf. = (adstock(t-1)*beta+spent(t))^alpha

## calcularemos com base no alpha e o beta

In [88]:
calculo_4 = df.copy()

calculo_4['FB_Transf'] =0.0
calculo_4['TV_Transf'] =0.0
calculo_4['Radio_transf'] =0.0

calculo dos coeficientes da linear regressão

In [89]:
import statsmodels.api as sm
import numpy as np


Alpha= 0.5
Beta = 0.2
Alpha_tv= 0.7 # diminuimos um pouco
Beta_tv = 0.1
Alpha_radio= 0.3  # diminuimos um pouco
Beta_radio = 0.2

calculo_4.loc[0,'TV_Transf'] = calculo_4.loc[0,'TV'] **Alpha_tv
calculo_4.loc[0,'Radio_transf'] = calculo_4.loc[0,'Radio'] **Alpha_radio
calculo_4.loc[0,'FB_Transf'] = calculo_4.loc[0,'FB'] **Alpha


for i in range(len(calculo_4) - 1):  # Adjusted to avoid going out of bounds
    calculo_4.loc[i + 1, 'FB_Transf'] = (calculo_4.loc[i, 'FB_Transf'] * Beta + calculo_4.loc[i + 1, 'FB']) ** Alpha
    calculo_4.loc[i + 1, 'TV_Transf'] = (calculo_4.loc[i, 'TV_Transf'] * Beta_tv + calculo_4.loc[i + 1, 'TV']) ** Alpha_tv
    calculo_4.loc[i + 1, 'Radio_transf'] = (calculo_4.loc[i, 'Radio_transf'] * Beta_radio + calculo_4.loc[i + 1, 'Radio']) ** Alpha_radio

# Definindo a variável dependente e as variáveis independentes
X = calculo_4[['FB_Transf', 'TV_Transf', 'Radio_transf']]  # Variáveis independentes
y = calculo_4['sales']  # Variável dependente

# Adicionando uma constante para o modelo
X = sm.add_constant(X)

# Criando o modelo de regressão
model = sm.OLS(y, X).fit()

# Imprimindo o resumo da regressão
print(model.summary())
# Obter o intercepto
intercept = model.params[0]  # O primeiro valor é o intercepto
print(f"Intercept: {intercept:.2f}")


# Obter e imprimir os coeficientes
coeficientes = model.params
print("\nCoeficientes do modelo:")
for variable, coef in coeficientes.items():
    print(f"{variable}: {coef:.2f}")
coeficientes_4 = model.params.to_dict()  # Converte os coeficientes para dicionário
print(coeficientes_4)
# Obter o valor de R²
r_squared = model.rsquared
print(f"R²: {r_squared:.5f}")

# Calcular o RMSE
predictions = model.predict(X)  # Previsões do modelo
rmse = np.sqrt(np.mean((predictions - y) ** 2))  # RMSE
print(f"RMSE: {rmse:.5f}")
print()
display(calculo_4)

                            OLS Regression Results
==============================================================================
Dep. Variable:                  sales   R-squared:                       0.923
Model:                            OLS   Adj. R-squared:                  0.914
Method:                 Least Squares   F-statistic:                     103.6
Date:                Tue, 05 Nov 2024   Prob (F-statistic):           1.40e-14
Time:                        23:02:22   Log-Likelihood:                -51.639
No. Observations:                  30   AIC:                             111.3
Df Residuals:                      26   BIC:                             116.9
Df Model:                           3
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
const           -1.8886      1.388     -1.361      0.185      -4.742       0.965
FB_Transf        0.9812      0.063     15.598      0.000       0.852       1.110
TV_Transf        0.7241      0.086      8.448      0.000       0.548       0.900
Radio_transf    -0.7399      0.514     -1.438      0.162      -1.797       0.317
==============================================================================
Omnibus:                        0.727   Durbin-Watson:                   2.160
Prob(Omnibus):                  0.695   Jarque-Bera (JB):                0.754
Skew:                           0.324   Prob(JB):                        0.686
Kurtosis:                       2.572   Cond. No.                         81.9
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
Intercept: -1.89

Coeficientes do modelo:
const: -1.89
FB_Transf: 0.98
TV_Transf: 0.72
Radio_transf: -0.74
{'const': -1.8885572197429252, 'FB_Transf': 0.9811948710835838, 'TV_Transf': 0.7241144786277885, 'Radio_transf': -0.7398762739920913}
R²: 0.92278
RMSE: 1.35304

/tmp/ipykernel_13636/511997271.py:35: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  intercept = model.params[0]  # O primeiro valor é o intercepto

,Time,sales,FB,TV,Radio,Date,FB_Transf,TV_Transf,Radio_transf
0,Week 1,22.1,230.1,37.8,69.2,2020-01-01,15.169047,12.712889,3.564773
1,Week 2,10.4,44.5,39.3,45.1,2020-01-02,6.894477,13.358361,3.149898
2,Week 3,9.3,17.2,45.9,69.3,2020-01-03,4.310324,14.859019,3.576012
3,Week 4,18.5,151.5,41.3,58.5,2020-01-04,12.343503,13.864700,3.401966
4,Week 5,12.9,180.8,10.8,58.4,2020-01-05,13.537677,5.755917,3.399641
5,Week 6,7.2,8.7,48.9,75.0,2020-01-06,3.377504,15.348774,3.661797
6,Week 7,11.8,57.5,32.8,23.5,2020-01-07,7.627287,11.885429,2.602068
7,Week 8,13.2,120.2,19.6,11.6,2020-01-08,11.032926,8.365210,2.113758
8,Week 9,4.8,8.6,2.1,1.0,2020-01-09,3.287337,2.125608,1.111575
9,Week 10,10.6,199.8,2.6,21.2,2020-01-10,14.158300,2.062393,2.507610
10,Week 11,8.6,66.1,5.8,24.2,2020-01-11,8.302509,3.507695,2.617081
11,Week 12,17.4,214.7,24.0,4.0,2020-01-12,14.709198,9.344561,1.572679
12,Week 13,9.2,23.8,35.1,65.9,2020-01-13,5.171251,12.294265,3.517920
13,Week 14,9.7,97.5,7.6,7.2,2020-01-14,9.926442,4.593595,1.859290
14,Week 15,19.0,204.1,32.9,46.0,2020-01-15,14.355671,11.648028,3.161377
15,Week 16,22.4,195.4,47.7,52.9,2020-01-16,14.080878,15.215888,3.300538
16,Week 17,12.5,67.8,36.6,114.0,2020-01-17,8.403343,12.788503,4.147856
17,Week 18,24.4,281.4,39.6,55.8,2020-01-18,16.825001,13.429167,3.356704
18,Week 19,11.3,69.2,20.5,18.3,2020-01-19,8.518509,8.659991,2.417850
19,Week 20,14.6,147.3,23.9,19.1,2020-01-20,12.206707,9.455818,2.440999
20,Week 21,18.0,218.4,27.7,53.4,2020-01-21,14.860732,10.469847,3.307106
21,Week 22,12.5,237.4,5.1,23.5,2020-01-22,15.503940,3.565033,2.599781
22,Week 23,5.6,13.2,15.9,49.6,2020-01-23,4.037423,7.042373,3.235960
23,Week 24,15.5,228.3,16.9,26.2,2020-01-24,15.136297,7.446155,2.683303
24,Week 25,9.7,62.3,12.6,18.3,2020-01-25,8.082528,6.133583,2.412688
25,Week 26,12.0,262.9,3.5,19.5,2020-01-26,16.263963,2.691148,2.455812
26,Week 27,15.0,142.9,29.3,12.6,2020-01-27,12.089367,10.705004,2.163184
27,Week 28,15.9,240.1,16.7,22.9,2020-01-28,15.572985,7.495313,2.572700
28,Week 29,18.9,248.8,27.1,22.9,2020-01-29,15.871818,10.265321,2.575406
29,Week 30,10.5,70.6,16.0,40.8,2020-01-30,8.589200,7.274252,3.053744

In [90]:
coeficientes_4

{'const': -1.8885572197429252,
 'FB_Transf': 0.9811948710835838,
 'TV_Transf': 0.7241144786277885,
 'Radio_transf': -0.7398762739920913}

## const = intercept

In [91]:
Alpha_FB= 0.5
Beta_FB = 0.2
Alpha_tv= 0.7 # diminuimos um pouco
Beta_tv = 0.1
Alpha_radio= 0.3  # diminuimos um pouco
Beta_radio = 0.2

In [92]:
calculo_4[0:29]['FB'].mean()

np.float64(139.32758620689657)

In [93]:
calculo_4[0:29]['TV'].mean()

np.float64(24.46896551724138)

In [94]:
calculo_4[0:29]['Radio'].mean()

np.float64(37.5551724137931)

In [95]:
simulador = pd.DataFrame([coeficientes_4])

In [96]:
simulador

      const  FB_Transf  TV_Transf  Radio_transf
0 -1.888557   0.981195   0.724114     -0.739876

In [97]:
simulador.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   const         1 non-null      float64
 1   FB_Transf     1 non-null      float64
 2   TV_Transf     1 non-null      float64
 3   Radio_transf  1 non-null      float64
dtypes: float64(4)
memory usage: 164.0 bytes

In [98]:
simulador['rotulo'] =''

In [99]:
simulador

      const  FB_Transf  TV_Transf  Radio_transf rotulo
0 -1.888557   0.981195   0.724114     -0.739876

In [100]:
simulador.loc[1,'rotulo'] = "Averages"

simulador.loc[1,'FB_Transf'] = calculo_4.loc[29,'FB']
simulador.loc[1,'TV_Transf'] = calculo_4.loc[29,'TV']
simulador.loc[1,'Radio_transf'] = calculo_4.loc[29,'Radio']

In [101]:
simulador

      const  FB_Transf  TV_Transf  Radio_transf    rotulo
0 -1.888557   0.981195   0.724114     -0.739876
1       NaN  70.600000  16.000000     40.800000  Averages

input é simular o quanto vamos gastar na campanha

In [102]:
simulador.loc[2,'rotulo'] = 'Input'

print('input novos dados para simular')

input novos dados para simular

In [103]:
simulador

      const  FB_Transf  TV_Transf  Radio_transf    rotulo
0 -1.888557   0.981195   0.724114     -0.739876
1       NaN  70.600000  16.000000     40.800000  Averages
2       NaN        NaN        NaN           NaN     Input

# o input é quanto queremos gastar em cada investiment, FB, TV ou Rádio

In [104]:
simulador.loc[2,'FB_Transf']  = float(input('Entrar com os dados de FB_Transf para simular'))
simulador.loc[2,'TV_Transf']  = float(input('Entrar com os dados de TV_Transf para simular'))
simulador.loc[2,'Radio_transf']  = float(input('Entrar com os dados de Radio_transf para simular'))

Entrar com os dados de FB_Transf para simular 160
Entrar com os dados de TV_Transf para simular 170
Entrar com os dados de Radio_transf para simular 120

In [105]:
simulador

      const   FB_Transf   TV_Transf  Radio_transf    rotulo
0 -1.888557    0.981195    0.724114     -0.739876
1       NaN   70.600000   16.000000     40.800000  Averages
2       NaN  160.000000  170.000000    120.000000     Input

Cáclulo do adstock

In [106]:
simulador.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   const         1 non-null      float64
 1   FB_Transf     3 non-null      float64
 2   TV_Transf     3 non-null      float64
 3   Radio_transf  3 non-null      float64
 4   rotulo        3 non-null      object
dtypes: float64(4), object(1)
memory usage: 252.0+ bytes

In [107]:
#??? posição da alpha e beta

simulador.loc[3,'rotulo'] = 'Transformed'


#Adstock(t)= Adstock (t-1)*beta+ Spent(t)
#Transf. = (adstock(t-1)*beta+spent(t))^alpha
# (média*beta+input)^alpha
simulador.loc[3,'FB_Transf']  = (simulador.loc[1,'FB_Transf']*Beta_FB + simulador.loc[2,'FB_Transf'])**Alpha_FB
simulador.loc[3,'TV_Transf']  = (simulador.loc[1,'TV_Transf']*Beta_tv + simulador.loc[2,'TV_Transf'])**Alpha_tv
simulador.loc[3,'Radio_transf']  = (simulador.loc[1,'Radio_transf']*Beta_radio + simulador.loc[2,'Radio_transf'])**Alpha_radio

In [108]:
simulador

      const   FB_Transf   TV_Transf  Radio_transf       rotulo
0 -1.888557    0.981195    0.724114     -0.739876
1       NaN   70.600000   16.000000     40.800000     Averages
2       NaN  160.000000  170.000000    120.000000        Input
3       NaN   13.195454   36.657437      4.288701  Transformed

In [109]:
simulador.loc[4,'rotulo'] = 'Contribution'

#   coef* Transformed
simulador.loc[4,'FB_Transf']  = (simulador.loc[0,'FB_Transf']* simulador.loc[3,'FB_Transf'])
simulador.loc[4,'TV_Transf']  = (simulador.loc[0,'TV_Transf']*simulador.loc[3,'TV_Transf'])
simulador.loc[4,'Radio_transf']  = (simulador.loc[0,'Radio_transf']* simulador.loc[3,'Radio_transf'])

simulador.loc[4,'const']  = (simulador.loc[0,'const']* 1)

In [110]:
simulador

      const   FB_Transf   TV_Transf  Radio_transf        rotulo
0 -1.888557    0.981195    0.724114     -0.739876
1       NaN   70.600000   16.000000     40.800000      Averages
2       NaN  160.000000  170.000000    120.000000         Input
3       NaN   13.195454   36.657437      4.288701   Transformed
4 -1.888557   12.947312   26.544181     -3.173108  Contribution

Sales prediction = soma toda a linha do contribuion

In [111]:
total_contribution = simulador.loc[simulador['rotulo'] == 'Contribution'].select_dtypes(include='number').sum(axis=1).values[0]
total_contribution

np.float64(34.429827338807414)

In [112]:
Sales_prediction = total_contribution

print('Sales prediction {}'.format(Sales_prediction))

Sales prediction 34.429827338807414

Cost é a soma dos inputs

In [113]:
Cost = simulador.loc[simulador['rotulo'] == 'Input'].select_dtypes(include='number').sum(axis=1).values[0]
Cost

np.float64(450.0)

In [114]:
print('Custo {}'.format(Cost))

Custo 450.0

CPO = Custo/Venda 

#cac

In [115]:
CPO = Cost/Sales_prediction

print('CPO: {}'.format(CPO))

CPO: 13.07006263992456

resultado em dinheiro

### otimização do investimento

https://blog.superlogica.com/assinaturas/cpl-cpo-cac-conheca-as-metricas-saas-de-aquisicao-de-clientes/

- Custo por Lead (CPL)

<b>Custo por Lead (CPL)</b> é uma métrica que estima quanto a empresa gasta por cada lead (usuário que demonstrou interesse em um conteúdo ou produto e compartilhou suas informações preenchendo um formulário) adquirido.

Veja bem: apenas um pequeno percentual dos leads se torna cliente de fato, então, por melhor que seja a taxa de conversão, o ideal é gerar muitos leads a um custo baixo.

#### CPL = total gasto com a captação dos leads / número de leads captados

Se a empresa gastou R$ 3 mil em marketing digital voltado à captação de leads e atraiu 350 pessoas, a conta fica assim:

#### CPL = 3.000 / 250

CPL = R$ 12

- Custo por Oportunidade (CPO)

Muitos leads podem apenas ter se interessado pelo conteúdo apresentado (em um ebook, por exemplo), mas não no valor que a empresa comercializa.

Quando ele avança no funil de vendas, demonstrando interesse também em um produto ou serviço, torna-se uma oportunidade de venda.

Assim, o <b>Custo por Oportunidade (CPO)</b> estima quanto se gasta, em média, para atrair esse lead qualificado.

- Custo de Aquisição de Clientes (CAC)

Essa métrica vai relacionar os investimentos feitos com o objetivo de atrair novos clientes com o número de pessoas que realmente assinaram um serviço da empresa.

Além de falar em clientes, ou seja, leads que foram convertidos, a diferença em relação à métrica anterior é que entram na conta também as despesas com as vendas.


#### CAC = custos com marketing e vendas / número de novos clientes

Digamos que a empresa gastou R$ 4.500 para atrair 50 clientes novos. A conta fica assim:

#### CAC = 4.500 / 50

CAC = R$ 90

O CAC será sempre maior que o CPL, pois os gastos que entram na conta são maiores, e o número de clientes é menor que o de leads gerados.